"""update post table

Revision ID: 295cc8e33335
Revises: e9b467a06c29
Create Date: 2024-09-03 00:02:36.410722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295cc8e33335'
down_revision = 'e9b467a06c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=500),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.String(length=500),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
